### ISSUE TITLE
I would appreciate it if you could tell me the reason for the error in "catkin_make"!

### ISSUE THREAD

**Issue by lgl-960709** [RISC-NYUAD/NE_UAScodes#2]
This is a great project!
I would appreciate it if you could tell me the reason for the error in "catkin_make"
![2022-04-07 17-09-01屏幕截图](https://user-images.githubusercontent.com/82514690/162164063-aa73a5d9-01c6-4198-9068-552e8484e3f6.png)
![2022-04-07 17-09-17屏幕截图](https://user-images.githubusercontent.com/82514690/162164088-1c53942d-8dec-4d21-8af9-d252e5d7f316.png)
!

**Comment by nevangeliouNYUAD** [comment]
This package is using the spinnaker sdk to stream images from a FLIR camera. Install Spinnaker SDK for cmake to be able find the include directories and libraries.
